[versions]
androidx_core_version = "1.12.0"
androidx_lifecycle_version = "2.7.0"
androidx_activity_compose_version = "1.8.2"
compose_version = "2023.08.00"
androidx_navigation_version = "2.7.7"
androidx_hilt_navigation_version = "1.1.0"
coil_compose_version = "1.3.2"
androidx_multidex_version = "2.0.1"
dagger_hilt_version = "2.48.1"
retrofit_version = "2.9.0"
okhttp_version = "4.11.0"
junit_version = "4.13.2"
mockk_version = "1.12.0"
espresso_core_version = "3.5.1"
gradle-versions = "0.51.0"

[plugins]
gradle-versions = { id = "com.github.ben-manes.versions", version.ref = "gradle-versions" }

